general:
  log_base_dir: logs/
  seed: 12345
  name: 2x-energy-force-b973c-no_new_data
  notes:
  mode: run    # debug, test or run
  project: ani

data:
  train:
    batch_size: 3000
    data_files: []
    data_dirs:
    - datasets/ANI2x-b973c-def2mtzvp
    data_dirs_ext: h5
    cache: false
    train_split: 0.8
    num_workers: 1
  test:
    batch_size: 300
    data_files: []
    data_dirs:
    - datasets/COMP6v2-b973c-def2mtzvp
    data_dirs_ext: h5
  info:
    elements: [H, C, N, O, S, F, Cl]
    self_energies: [-0.506930113968, -37.81441001258, -54.556538547322, -75.029181326588,
      -398.043159341582, -99.688618987039, -460.082223445159]

engine:
  type: ani_engine.engines.energy.EnergyEngine
  args:
    verbose: true
    train_force: true
    force_coefficient: 0.1
    use_tensorboard: true
    use_wandb: true
    additional_properties: []

model:
  type: ani_engine.models.energy.ANI
  args:
    version: ani2x
    cutoff_fn: cosine
    use_cuda_extension: true
    last_layer_bias: true
    use_mtl_loss: false

resume:
  from_dir:
  file_name: best_model.pt
  reset_lr: false

train:
  num_epochs: 15000
  optimizer:
    type: torch.optim.Adam
    args:
      lr: 0.00014
  lr_scheduler:
    type: torch.optim.lr_scheduler.ReduceLROnPlateau
    args:
      factor: 0.85
      patience: 100
      verbose: true
      threshold: 0.0001
      threshold_mode: rel
  early_stop_lr: 1e-5

auto:
  _id: 7avzat0g
  _name: 2x-energy-force-b973c-no_new_data
  date: '20230906_120322'
  log_dir: logs/run/20230906_120322-7avzat0g-2x-energy-force-b973c-no_new_data/
  tb_log_dir: logs/run/20230906_120322-7avzat0g-2x-energy-force-b973c-no_new_data/
  resume_file:
  checkpoint_file: 
    logs/run/20230906_120322-7avzat0g-2x-energy-force-b973c-no_new_data/checkpoint.pt
  best_model_file: 
    logs/run/20230906_120322-7avzat0g-2x-energy-force-b973c-no_new_data/best_model.pt
  config_file: logs/run/20230906_120322-7avzat0g-2x-energy-force-b973c-no_new_data/config.yaml
  ensemble:
    index:
    num:
    group:
