name: build_docker_base

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
      - 'build*'
      - 'external/**'
  repository_dispatch:
    types: [build-base-command]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_docker_base:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      # To avoid docker login and post login have race conditions because of multiple jobs running
      # on the same machine.
      - name: Set DOCKER_CONFIG
        run: |
          mkdir -p $HOME/.github_action_docker/${GITHUB_RUN_ID}/.docker
          echo "DOCKER_CONFIG=$HOME/.github_action_docker/${GITHUB_RUN_ID}/.docker" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to NGC Container Registry
        uses: docker/login-action@v2
        with:
          registry: nvcr.io
          username: $oauthtoken
          password: ${{ secrets.NGC_API_KEY }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          # push: ${{ github.event_name != 'pull_request' }}
          push: true
          pull: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-base:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MAKE_J_THREADS=5
            OVERRIDE_KOKKOS_ARCH=Kokkos_ARCH_AMPERE80
          target: base

      - name: Remove image
        if: ${{ always() }}
        continue-on-error: true
        run: echo # docker image rm ${{ steps.meta.outputs.tags }}

      - name: Post Set DOCKER_CONFIG
        if: ${{ always() }}
        run: rm -rf $HOME/.github_action_docker/${GITHUB_RUN_ID}

concurrency:
  group: build_docker_base-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
